### ISSUE TITLE
Qdrant Image blocking in ACI

### ISSUE THREAD

**Issue by tawalke** [Azure-Samples/qdrant-azure#18]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Qdrant image is public on DockerHub, but when image attempted to be retrieved from ACI it notes inaccessible image.  The image has been verified to be: 
* Public
* Available for download via docker pull
* Available for use as image in AKS
* Not in restricted repo or account in Docker
* Has happen in various types of Azure Subscriptions 

### Any log messages given by the failure
> 

![Qdrant-ACI-image-error](https://user-images.githubusercontent.com/2299606/223828542-c1ca94c3-5b67-439b-b6de-04ebd5c0b15a.png)

### Expected/desired behavior
> The image is pulled an deployed in a similar fashion as it would be in Docker or K8s/AKS
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luisquintanilla** [comment]
+1. I'm seeing the same issue. 

![image](https://user-images.githubusercontent.com/46974588/231484754-0bee38c5-ada6-4f78-878e-76954252897f.png)

**Comment by drhoussem** [comment]
I faced the same issue

**Comment by tawalke** [comment]
> I faced the same issue

Yes, we have diagnosed the issue and it was noted that a possible fix exists now. Please retry. 

Additionally we have added other options.
