### ISSUE TITLE
Invalid Key Pair Name

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/qdrant-azure#20]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- Deploy Qdrant to AKS
- Use qdrantssh as ssh key-pair name

### Any log messages given by the failure
>

![image](https://user-images.githubusercontent.com/46974588/231488357-5e31aa5d-1580-4092-a592-fd624901076e.png)

### Expected/desired behavior
> Qdrant resource is deployed successfully

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tawalke** [comment]
@luisquintanilla: Please review updates to Readme.md and let me know if the steps are clearer.

**Comment by tawalke** [comment]
Thanks @luisquintanilla for the great review and walkthrough. I think the resolution we came up with will be great for customers. I'll create a PR with this change and add your review.

**Comment by luisquintanilla** [comment]
Thank you!

**Comment by tawalke** [comment]
Updated documentation, verified it's working. Closing issue.
